version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artify_backend
    ports:
      - "8000:8000"
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artify_ui
    ports:
      - "8501:8501"
