apiVersion: v1
kind: Service
metadata:
  name: artify-frontend-service
spec:
  selector:
    app: artify-frontend
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: NodePort  # Change to LoadBalancer for production
